### ISSUE TITLE
Set volume to 100% in setup script

### ISSUE THREAD

**Issue by Robotopera** [adangert/JoustMania#125]
Finally got some playtime on my setup over the weekend and the volume was very low, even with the amp at 100%. This was resolved by increasing the volume to 100% using `amixer  sset PCM,0 100%` It might be useful to include this in the setup script to ensure proper sound output.

**Comment by adangert** [comment]
that's a great idea! usually I just click the audio icon at the top and then drag the slider all the way up. Also I usually have to set it from HDMI to analog. If you wanna put that in the setup.sh in a PR go for it

**Comment by Robotopera** [comment]
PR created
