### ISSUE TITLE
refactor DRY game mode code into seperate files

### ISSUE THREAD

**Issue by adangert** [adangert/JoustMania#162]
a bunch of code could be refactored into it's own dedicated files, this was started with player.py, pacemaker.py and controller_util files.

**Comment by Nam-Ereh-Won** [comment]
I'm working on consolidating the music and sfx code as part of a feature to upload and manage music via the webUI.

**Comment by adangert** [comment]
Great fix from @mchirlin from #317 Updated and merged in
