### ISSUE TITLE
No Sound Mode?

### ISSUE THREAD

**Issue by hdsjulian** [adangert/JoustMania#165]
As JoustMania is now _vastly_ better than Oust: I'd really like to have a mode that doesn't require sound. For Festivals and other noisy (or especially quiet) environments. 
Any chance this can be done easily?

**Comment by adangert** [comment]
Yeah, changing audio = False in joustconfig.ini should turn most of the game modes silent, and remove tempo and sensitivity changes during the game.

**Comment by hdsjulian** [comment]
\o/
