### ISSUE TITLE
Feature Request - Change to Admin Mode/Game toggle.

### ISSUE THREAD

**Issue by ChainmailBuddha** [adangert/JoustMania#167]
Currently the select button is used to simultaneously change game mode, as well as to enable admin mode.
This results in the scenario of having to cycle through all game modes when someone wants to perform an admin function, but continue playing the same game mode.

Would it be possible to change this behavior such that the first press of the Select button after any given game only enables admin, then subsequent presses toggle the game mode.
This would allow a quick toggle of instructions, sensitivity, or battery check, without having to necessarily cycling through all modes, while only adding a single press to the sequence of cycling games. This could also have the added benefit of helping to prevent accidental game changes if someone presses the Select button by mistake.

**Comment by adangert** [comment]
yeah that's a really good point. Perhaps an even better idea is that pressing select changes game modes, but holding in select turns you into an admin after a second or two.

**Comment by ChainmailBuddha** [comment]
That could totally work. There is also that pesky Start button on the other side just hanging out and doing nothing. Lazy bugger. :)

**Comment by adangert** [comment]
holding in start then would seem best, I would think.

**Comment by ChainmailBuddha** [comment]
That does sound good. 
Then we also do not have anyone accidentally changing settings when they only meant to change game modes.

Alternately, if we want to avoid any accidental changes we could have a long press of Start (or even Select <insert whynotboth.gif> ) activate admin mode. Which not only enables the face buttons, but also mode select via the Select button. This would help prevent curious players from just smashing buttons and causing issues.

**Comment by adangert** [comment]
hmm, I think leaving it as just one press for changing game modes is probably fine, especially for individuals who just got joustmania setup, and don't want to read the manual for how to change game modes. We previously had the start button assigned to starting games, but then that introduced the problem of griefers starting game modes automatically, so it was taken out. At best it's a minor social annoyance that I think group mentality would stop someone from doing it out of spite, or else they will get their controller taken away.

**Comment by adangert** [comment]
another idea, is perhaps to eventually just upgrade to controlling the game through the phone itself, then that would solve most problems, but I think having psmove controls is still a good idea for now.

**Comment by adangert** [comment]
I mean I agree, the only time that would happen I think, is if we could get phone support as controllers for the game: https://github.com/adangert/JoustMania/issues/88

That way the cost of playing joustmania goes way down, and the amount of players that can play goes up. It would be reasonable at that time to start to transition things more towards the phone aspect.

**Comment by ChainmailBuddha** [comment]
I for one am terrified of the idea of using phones as controllers. I know how rough the game can get, and we require the use of lanyards on all controllers for all players. Phones are even more awkward/difficult to use etc. Not only that, I feel like losing the lights at the top of the controllers would be detrimental to the entire experience.

I am more looking forward to the open source controllers that Martin is working on: #141
Full disclosure though, Martin is a friend of mine.

**Comment by adangert** [comment]
Well yeah I definitely get where you are coming from. However many people I've talked with won't get any sort of joust setup, even if they would like to, because of the price of the controllers, it's the most expensive part to joustmania at the moment. Allowing phones as a choice, in any case is a good thing in my opinion, as well as the official ps move controllers, and those awesome open source controllers Martin is working on :p  

Some things that could remedy the situation, would defaulting to high sensitivity when any phones are involved, Perhaps there could also be a cheap strap that one could buy for many phones that could clip on in some way.

For the color problem, turning the entire screen of the phone one color, for better visibility could work. A plastic dome or pyramid could also be looked at, that would be taped down to the front of the phone in order to "broadcast" the color to everyone, similar to the psmove controllers. Thus for a tiny piece of plastic and a cheap strap, you could turn any phone into a joust controller for a dollar or two.

**Comment by ChainmailBuddha** [comment]
Oh, I totally get where you, and these people are coming from, and I fully support the effort. Far be it for me to deny anyone choices. I was just stating my own fears etc. :)

I also understand the barrier to entry. That is exactly why I just built a kit as soon as I could afford it. Just to keep it alive on my annual nerd boat cruise, as well as to introduce it to new players as often as possible.

**Comment by ChainmailBuddha** [comment]
Just another thought on this one. I have had a few games recently that did not auto start, even though all active controllers have toggled in. I have not had a chance to troubleshoot or track down a possible cause for this.

However it got me thinking of your comment about formerly having the Start button for starting games. Perhaps if you add in the long press for admin then the Start=start could be added back in, but only while in admin mode and only for the admin controller. Thoughts?

**Comment by ChainmailBuddha** [comment]
Oh I totally agree with you on this particular issue.
It just gave me the thought that adding the feature back in under the admin settings might otherwise been useful. The rest was just for context on my random thought. :)

**Comment by adangert** [comment]
Maybe, I'd have to think where it would work better than just having the game start when everyone is ready.

**Comment by ChainmailBuddha** [comment]
Well, another use case is one which I have also had recently, in which I did not have an excess of players, and some people that wanted to sit out just a single round or two. 
When disengaging controllers by pressing all four face buttons, it can be tricky getting them activated again. The only way I can reliably seem to do so is pressing the PS button long enough for them to reactivate, but no so long that the controllers turn off. (On a side note, controllers which are turned off do not seem to want to reconnect to the game, even though they successfully re-pair with the rasppi when powered back up)

In this case, I feel it would be useful to simply start the next game, while those individuals sit out for a bit. And yes I am aware that I can do so from the web interface, and have, this is less convenient that merely entering admin mode, and the hitting start.

Again, just my opinion and suggestion.

**Comment by adangert** [comment]
Oh hey, yeah I suppose I should put that in the readme, but you only need to press the PS button once, and then the controller will connect again automatically in a couple of seconds, no need to hold down. That process should be communicated better I think.

**Comment by adangert** [comment]
Added in newest update, changing game modes will not turn you into an admin, you can become one by pressing all four front buttons.
