### ISSUE TITLE
Suspended controllers still show the visual countdown at the start of games.

### ISSUE THREAD

**Issue by ChainmailBuddha** [adangert/JoustMania#184]
If a controller is suspended (pressing all four face buttons) the controller light goes off as expected, and this controller no longer counts for starting games. However when a game is started the suspended controller still shows the red, yellow, green light countdown as if it were active and in the game. Post countdown the controller light goes back off and game play is unaffected.
This issue appears to be cosmetic only and does not affect game play. However it can cause some confusion among players when it occurs.

**Comment by adangert** [comment]
This was fixed in a previous update
