### ISSUE TITLE
Change the number of players per team

### ISSUE THREAD

**Issue by sizzlersam** [adangert/JoustMania#193]
Is there a way to specify the number of players per team (or just number of teams)? As of now it seems to automatically pick a number of teams based on player count and we'd love to have an 8 vs 8, 6 vs 6 vs 6, or other game or similar variants.

**Comment by adangert** [comment]
heya, in regular teams mode each person can manually select the team they would like to be on by pressing the middle button on the controller, their team color will change before the game begins. Thus you can have an 8v8, 6v6 or any other type of setup.
