### ISSUE TITLE
when joustmania starts have it notify the player if there is an update available.

### ISSUE THREAD

**Issue by adangert** [adangert/JoustMania#198]
So they can update it on their own time, perhaps have a button to update joustmania when it boots up too.

**Comment by adangert** [comment]
hold in start and select for three seconds to update.

**Comment by ChainmailBuddha** [comment]
How would this work out though for those who leave it in AP mode most of the time?

**Comment by adangert** [comment]
I think that it would only check for updates when connected to the internet. so you would have to switch it over or plug in an ethernet cord.

**Comment by SkyroOryks** [comment]
This a good idea, since the git pull takes a little bit of a process. And like me one forgets to do it.

**Comment by ChainmailBuddha** [comment]
Perhaps have it keep a record of the last time it attempted to update, and have an audio prompt on startup if it has not checked for an update in a certain period of time, such as 30 days or so.
Just as a reminder for those who don't always connect it to a network.

**Comment by adangert** [comment]
Joustmania now will check for updates on startup, and update the program if it is a small update, it will prompt the user to update on a larger update.
