### ISSUE TITLE
Upgrade to raspian buster

### ISSUE THREAD

**Issue by adangert** [adangert/JoustMania#226]

**Comment by adangert** [comment]
updated to raspbian buster, works on the raspberry pi 4 now

**Comment by supersmo** [comment]
I can confirm that it works on raspbian buster on raspberry pi 3 model b+.
Thanks.
CPU utilization is high and I get the "[Over temperature warning (80-85C)](https://www.raspberrypi.org/documentation/configuration/warning-icons.md)"
(Maybe I should've gotten a raspberry pi 4 instead.)
