### ISSUE TITLE
Don't disable Bluetooth without asking the user first

### ISSUE THREAD

**Issue by lmore377** [adangert/JoustMania#228]
In the README it says that a USB Bluetooth dongle is optional, but by disabling the onboard bluetooth in the setup script you're essentially making it a requirement for people who can't edit out that part because they don't really know all that much about Linux

**Comment by adangert** [comment]
Good point, it probably should be a command line option for the setup.sh, I'll change it in the next update

**Comment by adangert** [comment]
updated now you need to put in the command --disable_internal_bt when running the setup to disable the internal bluetooth.
