### ISSUE TITLE
random crashes when starting some games

### ISSUE THREAD

**Issue by adangert** [adangert/JoustMania#24]
sometimes when starting a game the pi crashes,
perhaps try putting a time.sleep in between new controller processes in each game?

**Comment by adangert** [comment]
looks like it might be because of  CPU spikes when python makes a bunch of processes, perhaps limiting the processes would help, the game usually shuts off within the first 10 minutes of starting the game, and looks like it crashes less when there is no screen attached.

**Comment by adangert** [comment]
also could be related to heat/memory issues the pi is experiencing under stress, investigation is needed.

**Comment by adangert** [comment]
Looks like it is due to a memory allocation error.

**Comment by adangert** [comment]
There could be a memory leak in the code somewhere, investigation would be necessary

**Comment by adangert** [comment]
@chaintip

**Comment by chaintip** [comment]
`0.00518358 BCH`| `~   6.73 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4rxyvqxlcpcc9anfdvh8sg744kqysflydp4k) to this issue by @adangert.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/22), get a pull request merged with ```@chaintip fixes #24``` in the creation comment.

**Comment by chaintip** [comment]
The fiat value for this is incorrect. Will update soon.

**Comment by block-spider** [comment]
@chaintip 2 days

**Comment by chaintip** [comment]
Thank you @block-spider! `0.00994548 BCH`| `~  10.45 USD` has now been tipped to this issue.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/22), get a pull request merged with ```@chaintip fixes #24``` in the creation comment.

**Comment by chaintip** [comment]
`0.00518358 BCH`| `~   5.53 USD` has now been tipped to this issue.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/22), get a pull request merged with ```@chaintip fixes #24``` in the creation comment.

**Comment by derianalanrojas** [comment]
The stress of the processing could also be due to the type of CPU processor often influences too much

**Comment by chaintip** [comment]
`0 BCH`| `~   0.00 USD` has now been tipped to this issue.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/22), get a pull request merged with ```@chaintip fixes #24``` in the creation comment.

**Comment by adangert** [comment]
Fixed with stability update
