### ISSUE TITLE
Could the Audio mix be adjusted via the web inteface?

### ISSUE THREAD

**Issue by TheMiniBar** [adangert/JoustMania#242]

**Comment by TheMiniBar** [comment]
Strike sounds are so loud or some sound systems that the music and voice comments are hard to hear. Being able to adjust these three types of audio would be great

**Comment by adangert** [comment]
what are strike sounds?

**Comment by TheMiniBar** [comment]
Sorry, my name for the sound the Pi plays when a PS Move controller is hit.

**Comment by adangert** [comment]
I might be able to turn down that volume, you can do it manually via changing https://github.com/adangert/JoustMania/blob/master/audio/Joust/sounds/Explosion34.wav right now

**Comment by TheMiniBar** [comment]
Ah cool. I was wondering whether. Voice instructions and could be put more on (for example) the right side of a stereo channel, and music on the other side (eg left) and then some sound systems with balance control could easily adjust the mix.  Just a thought. 

I might try toning down the volume of the explosion.wav if I can find suitable software. Individually people know when they are “hit” generally anyway. 

Thanks for all your efforts. 👍😀👍

**Comment by TheMiniBar** [comment]
I can't upload WAV files here, what's the best way to send you the modified Explosion sounds?

**Comment by TheMiniBar** [comment]
Just noticed after copying the modified explosion sounds that Joust announces “Joust Updated” (or similar) every time it boots up. Is there any implications from that message? (Eg my file gets overwritten after reboot, or I won’t get updates in future?). @adangert

**Comment by adangert** [comment]
Oh you can make a pull request in another branch to upload the files. Also the updater just checks if files have been changed to do a pull request, so you should be fine, it will still update correctly. You can add the files to the .gitignore file to stop it checking those files.

**Comment by adangert** [comment]
Lowered the volume of Explosion34.wav in the latest commit.
