### ISSUE TITLE
only do an update for new files on the GitHub rather than modified files

### ISSUE THREAD

**Issue by adangert** [adangert/JoustMania#248]
This way people can update their installation without hearing it's been updated every time

**Comment by TheMiniBar** [comment]
This would be nice. With my quietened Explosion34.wav file. I've not managed to work out how to list the modified file in the git exclusion list so do get the message every time

**Comment by adangert** [comment]
Updated in newest commit, it should only say that it's been updated for new files, not ones you've modified.
