### ISSUE TITLE
Game/Pi crashes when adding controllers after games have been played.

### ISSUE THREAD

**Issue by ChainmailBuddha** [adangert/JoustMania#254]
New issue since the last Force Start fix. I can add any number of controllers when the game is first started up, and play just fine. However, when turning on and adding additional controllers after one or more games have been played intermittently causes either Joust or the Pi to hang/crash. Music stops, AP becomes non-responsive, and nothing else works. A hard reboot of the Pi is required to recover from this failure mode.
This occurred both when trying to add controllers during an active game, or between games while at the menu music. Issue was intermittent, but very repeatable.

**Comment by adangert** [comment]
Issue should now be fixed, tested on free for all.
