### ISSUE TITLE
ModuleNotFoundError: No module named '_psmove'

### ISSUE THREAD

**Issue by jango-fx** [adangert/JoustMania#291]
I tried to install JoustMania on a RasberyPi 4 b 8Gb.
Newly installed latest version of Pi OS 
I have run and rerun setup.sh.

The auto-start doesn't happen at all and if i try to manually run any of the scripts via
```
python ./piparty.py
sudo python ./piparty.py
python3 ./piparty.py
sudo python3 ./piparty.py
./venv/bin/python ./joust.py
sudo ./venv/bin/python ./joust.py
```

it always fails with 
```
ModuleNotFoundError: No module named '_psmove'
```
i believe i used to fail with
```
ModuleNotFoundError: No module named 'psmove'
```
until i manually built psmoveapi. but the `_psmove.pyd` that is supposed to be created does not exist.

now i'm completely lost.
the manually built psmove binary seems to work and at least detect the controllers when connected via usb. the psmoveapi python examples won't work though... and i can't determine with certainty if the controllers are paired…

**Comment by adangert** [comment]
Hi I've just made some updates to the install script, usually you can start joustmania with the command ./joust.sh inside the JoustMania folder

See if that helps, or try to reclone and reinstall joustmania again

**Comment by jango-fx** [comment]
hah! reclone+install did the trick now! 
thx for the quick response. much appreciated 🙏 

now i'm wondering though: can i stop the auto-started game somehow?

**Comment by adangert** [comment]
Yes sudo ./kill_processes.sh should do the trick, if you look in /etc/supervisor there are all the files for joustmania running automatically on startup. I hope that helps!
