### ISSUE TITLE
Bluetooth failing to start on debian due to SAP (sap-server: Operation not permitted)

### ISSUE THREAD

**Issue by NetSpida** [adangert/JoustMania#303]
Due to a [bug/decision in debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=803265), the SIM Access Protocol is enabled in the bluetooth stack, but parts of the system are lacking privileges to access it. This results in the following error messages and a failed service -- one rather important for joustmania.

```
bluetoothd[86427]: Bluetooth daemon 5.55
systemd[1]: Started Bluetooth service.
bluetoothd[86427]: Starting SDP server
bluetoothd[86427]: Bluetooth management interface 1.18 initialized
bluetoothd[86427]: profiles/sap/server.c:sap_server_register() Sap driver initialization failed.
bluetoothd[86427]: sap-server: Operation not permitted (1)
```
A more [detailed analysis of the SAP missing permission is available on stackexchange](https://unix.stackexchange.com/questions/705326/debian-11-bluetooth-sap-driver-initialization-failed)

**Comment by adangert** [comment]
Closing from this [here](https://github.com/adangert/JoustMania/pull/304#issuecomment-1712654022), I think if we find more issues with Debian we can help out by adding to the wiki. I've added a link to the Debian wiki in the Joustmania main readme [here](https://github.com/adangert/JoustMania/commit/1ba4aa13325da88970943e16f6297b4e7384d1c6)
