### ISSUE TITLE
Web admin settings don't update if changed by another web browser/Move controller

### ISSUE THREAD

**Issue by ericbuzan** [adangert/JoustMania#62]
Currently the backend doesn't send the status of admin settings to the web GUI so changes cannot be viewed.

**Comment by adangert** [comment]
hmm, I had the pi's browser set to 0.0.0.0 and was at joust.mania on my phone. When I changed the game type on my phone it updated on the pi web browser.

**Comment by ericbuzan** [comment]
Bad wording on my part. I mean the admin settings page doesn't update when changed from elsewhere. The game status should update properly on every connected browser.

**Comment by adangert** [comment]
ah, yeah that makes more sense.

**Comment by ericbuzan** [comment]
This is fixed with the recent web ui update. The settings page does not live update, but will if the page is refreshed.
