### ISSUE TITLE
Joustmania on Windows

### ISSUE THREAD

**Issue by adangert** [adangert/JoustMania#67]

**Comment by adangert** [comment]
https://github.com/thp/psmoveapi/pull/313 was just fixed, this may make it easier to implement joustmania on windows.

**Comment by adangert** [comment]
Currently is blocked by some issues with psmove on Windows, here: https://github.com/thp/psmoveapi/issues/314 and here: https://github.com/thp/psmoveapi/issues/214

**Comment by mbabinski-at-google** [comment]
FWIW, JS Joust was never released on Windows because Microsoft kernel engineering claimed that the bluetooth stack doesn't support what's required.

https://arstechnica.com/gaming/2014/12/microsoft-tells-j-s-joust-devs-their-game-is-not-possible-on-windows/

**Comment by martinbogo** [comment]
@adangert The PSmove just won't work on the Windows bluetooth stack ... even the newest win10 creator enhancements don't help.

**Comment by adangert** [comment]
There is a dll that seems like it can be implemented: https://github.com/thp/psmoveapi/issues/355

**Comment by adangert** [comment]
updated and working in windows branch.
