### ISSUE TITLE
Non stop Joust mode

### ISSUE THREAD

**Issue by adangert** [adangert/JoustMania#72]
Players respawn after a short period of time, after a couple of minutes which ever player died the fewest wins.

**Comment by MrAbodi** [comment]
Ah this is cool

**Comment by martinbogo** [comment]
This, is a beautifully (evil) idea.   Will depend heavily on a simpler "add/remove" player mechanism from the controller as well, because a player has to be able to permanently drop out of a longer ( >3-5 minute ) game if they need to walk away w/o penalizing everyone else.

**Comment by adangert** [comment]
added non stop joust mode. It's currently set to 2.5 minutes per game with a countdown near the end.
